services:
  mongodb:
    image: mongo:7
    container_name: tfm-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: bigdataspark
    volumes:
      - ./data:/data/db
    restart: unless-stopped